// Auto-generated configuration file. Do not edit directly.
window.CONFIG = {
  "TITLE": "QSBkaWdpdGFsIHNjcmFwYm9vaw==",
  "SUBTITLE": "QSBsaXR0bGUgYnJlYWsgZnJvbSB0aGUgaG9zcGl0YWwgd2FyZHMg8J+MuA==",
  "OPEN_BTN_TEXT": "T3BlbiBtZSDwn5GA",
  "PAGE_DATE": "SnVuZSAyMDI2",
  "JOURNAL_TITLE": "QSBMaXR0bGUgTWVzc2FnZS4uLiDwn5Od",
  "JOURNAL_ENTRIES": [
    "SGV5IEhpcmEhIPCfjLgKCkkgYnVpbHQgdGhpcyBzbWFsbCBzcGFjZSB0byBnaXZlIHlvdSBhIHF1aWNrIGJyZWFrIGZyb20gdGhlIGhvc3BpdGFsIHdhcmRzIGFuZCBib29rcy4gWW91IHdvcmsgc28gaW5jcmVkaWJseSBoYXJkIGluIG1lZCBzY2hvb2wuIEhlcmUgaXMgYSBjb3p5IGNvcm5lciB0byBtYWtlIHlvdSBzbWlsZSB3aGVuZXZlciB5b3VyIGNsaW5pY2FsIHJvdXRpbmVzIGdldCBjaGFvdGljIQ==",
    "RnJvbSBjcnlpbmcgYWJvdXQgdXBjb21pbmcgdGVzdHMgYW5kIHVub2JzIHRvIGNvbXBsZXRlbHkgYWNpbmcgdGhlbSwgeW91IGRvIGl0IGFsbCEgSSdtIHNvIHByb3VkIG9mIHlvdXIgZGVkaWNhdGlvbiAoYW5kIG91ciBjb21iaW5lZCBhYmlsaXR5IHRvIHJ1biBhd2F5IGZyb20gaG9zcGl0YWwgcm91bmRzKS4gWW91J3JlIGdvaW5nIHRvIG1ha2UgYW4gYW1hemluZyBkb2N0b3IhIPCfqbrinKg=",
    "VGhhbmtzIGZvciBiZWluZyB0aGUgYmVzdCBsYXRlLW5pZ2h0IHJhbnRlci4gVGFrZSBhIG1vbWVudCB0byBwbGF5IHNvbWUgbG9maSBiZWF0cywgc2xpZGUgc29tZSBzdGlja2VycyBhcm91bmQsIGFuZCBpZ25vcmUgdGhlIHN0dWR5IHN0cmVzcyBmb3IgYSBiaXQuIFlvdSd2ZSBnb3QgdGhpcyEg8J+QsQ=="
  ],
  "POLAROID_1_CAPTION": "V2FyZHMgRXNjYXBlZSDwn6m68J+Pg+KAjeKZgO+4jw==",
  "POLAROID_2_CAPTION": "VW5vYnMgJiBDb2ZmZWUg8J+TluKYle+4jw==",
  "POLAROID_3_CAPTION": "MiBBTSBDaGFvdGljIFRhbGtzIPCfjJnwn5Ks",
  "POLAROID_3_TEXT_1": "QWhoaCE=",
  "POLAROID_3_TEXT_2": "U2FtZSBsb2w=",
  "LETTER_TITLE": "RGVhciBIaXJhLCDwn6m68J+SnQ==",
  "LETTER_PARAGRAPHS": [
    "SSBrbm93IGNsaW5pY2FsIHJvdGF0aW9ucywgbG9uZyB3YXJkIGhvdXJzLCBhbmQgc3RyZXNzZnVsIGV4YW1zIGNhbiBiZSBjb21wbGV0ZWx5IGRyYWluaW5nLg==",
    "WWV0LCB5b3UgaGFuZGxlIGl0IGFsbCB3aXRoIHNvIG11Y2ggaHVtb3IsIHN0cmVuZ3RoLCBhbmQgZ3JhY2UuIFRoYW5rIHlvdSBmb3IgYWx3YXlzIGJlaW5nIGRvd24gdG8gdGV4dCBsYXRlIGF0IG5pZ2h0LCBoYXZpbmcgcmFuZG9tIG1vb2Qgc3dpbmdzLCBhbmQgc2hhcmluZyB0aGUgZGFpbHkgY2hhb3MuIFlvdSdyZSBhbiBpbmNyZWRpYmxlIGZyaWVuZCE=",
    "UmVtZW1iZXIgdG8gdGFrZSBhIGJyZWFrLCBnZXQgc29tZSBzbGVlcCAoc2VyaW91c2x5ISksIGFuZCBrbm93IHRoYXQgSSdtIGFsd2F5cyBjaGVlcmluZyB5b3Ugb24uIFlvdSdyZSBnb2luZyB0byBtYWtlIGFuIGFtYXppbmcgZG9jdG9yISDwn4yf"
  ],
  "LETTER_SIGNATURE": "QnllZWUhISHwn6Ww",
  "MUSIC_TITLE": "Q296eSBCZWF0cw==",
  "STICKER_PANEL_TITLE": "QWRkIFNvbWUgQ3V0ZSBTdGlja2VycyEg8J+RhyAoRHJhZyBvciBUYXAp"
};
